version: '3.9'

services:
  telegram_bot:
    build:
      context: .
    environment:
      TELEGRAM_API_KEY: "${TELEGRAM_API_KEY}"
      OPEN_AI_KEY: "${OPEN_AI_KEY}"
      MONGO_DB_PASSWORD: "${MONGO_DB_PASSWORD}"
      PORT: 8000
    ports:
      - "8000:8000"
  hello_world_server:
    image: python:3.9-slim
    command: /bin/sh -c 'echo "<h1>Hello, World</h1>" > index.html && python -m http.server 3000 --bind 0.0.0.0'
    ports:
      - "3000:3000"